setwd("~/R_projektit")
library("magick", lib.loc="~/R/win-library/3.5")
dog <-image_read('https://maailmaataviksensilmin.files.wordpress.com/2017/07/img_9618.jpg?w=1536')
image_flip(dog)
print (dog)
dog2 = image_flip(dog)
print (dog2)
Sys.sleep(2)
print (dog)
image_write (dog,path = "C:/Users/pomik/OneDrive/Tiedostot/R_projektit/dog.png", format = 'png')
image_write (dog2,path = "C:/Users/pomik/OneDrive/Tiedostot/R_projektit/dog2.png", format = 'png')          